services:
  batocera_builder:
    image: melviserpa/batocera.linux-build:latest
    container_name: batocera_builder
    stdin_open: true
    tty: true
    volumes:
      - ${HOME}/batocera.linux:/src/batocera.linux
      - ${HOME}/.ssh:/root/.ssh
    command: /bin/bash



